[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
empty = "UAiCybB7jm6dHZBrGQotghGAHj82hZnvKZhFMjRtsBp"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/bilalafzal/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
